# Generated by Django 6.0 on 2026-01-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sprint_name', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=64)),
                ('end_date', models.CharField(max_length=64)),
                ('sprint_goal', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sprints',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=64)),
                ('avatar', models.CharField(blank=True, max_length=1024, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='SprintSummary',
            fields=[
                ('sprint', models.OneToOneField(db_column='sprint_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.sprint')),
                ('planned_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('carry_forward', models.IntegerField(default=0)),
                ('additional_tasks', models.IntegerField(default=0)),
                ('bugs', models.IntegerField(default=0)),
                ('success_percentage', models.FloatField(default=0)),
                ('what_went_well', models.TextField(blank=True, null=True)),
                ('issues', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('completed_date', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'sprint_summaries',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=64)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('estimated_hours', models.FloatField(default=0)),
                ('actual_hours', models.FloatField(default=0)),
                ('blocker', models.TextField(blank=True, null=True)),
                ('blocker_date', models.CharField(blank=True, max_length=64, null=True)),
                ('created_date', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('sprint', models.ForeignKey(blank=True, db_column='sprint_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sprint')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teammember')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_date', models.CharField(max_length=64)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='api.task')),
                ('author', models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teammember')),
            ],
            options={
                'db_table': 'task_comments',
            },
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teammember')),
            ],
            options={
                'db_table': 'session_state',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('task', models.OneToOneField(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.task')),
                ('reason', models.TextField(blank=True, null=True)),
                ('impact', models.CharField(blank=True, max_length=32, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.teammember')),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
    ]
