# Generated by Django 6.0 on 2026-01-02 13:07

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def migrate_teammembers_to_users(apps, schema_editor):
    TeamMember = apps.get_model('api', 'TeamMember')
    Task = apps.get_model('api', 'Task')
    Approval = apps.get_model('api', 'Approval')
    TaskComment = apps.get_model('api', 'TaskComment')
    UserModel = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    MemberProfile = apps.get_model('api', 'MemberProfile')

    id_map = {}
    # Drop old FK constraints to allow remapping
    schema_editor.execute('ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_owner_id_fkey;')
    schema_editor.execute('ALTER TABLE approvals DROP CONSTRAINT IF EXISTS approvals_approved_by_fkey;')
    schema_editor.execute('ALTER TABLE task_comments DROP CONSTRAINT IF EXISTS task_comments_author_id_fkey;')
    # Create users and profiles for existing team members
    for tm in TeamMember.objects.all():
        user, _ = UserModel.objects.get_or_create(
            username=tm.username,
            defaults={
                "first_name": tm.name or tm.username,
                "email": "",
                "password": make_password("password123"),
            },
        )
        MemberProfile.objects.update_or_create(
            user=user,
            defaults={
                "role": getattr(tm, "role", "Developer") or "Developer",
                "avatar": getattr(tm, "avatar", None),
            },
        )
        id_map[tm.id] = user.pk

    # Update foreign keys to point to new users
    for task in Task.objects.all():
        if task.owner_id and task.owner_id in id_map:
            task.owner_id = id_map[task.owner_id]
            task.save(update_fields=["owner"])
    for approval in Approval.objects.all():
        if approval.approved_by_id and approval.approved_by_id in id_map:
            approval.approved_by_id = id_map[approval.approved_by_id]
            approval.save(update_fields=["approved_by"])
    for comment in TaskComment.objects.all():
        if comment.author_id and comment.author_id in id_map:
            comment.author_id = id_map[comment.author_id]
            comment.save(update_fields=["author"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Developer', max_length=64)),
                ('avatar', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_profiles',
            },
        ),
        migrations.RunPython(migrate_teammembers_to_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(blank=True, db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SessionState',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
