# Generated by Django 6.0 on 2026-01-12 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_set_user_emails"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=512)),
                ("file_size", models.BigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=255, null=True)),
                ("s3_bucket", models.CharField(max_length=255)),
                ("s3_key", models.CharField(max_length=1024)),
                ("created_date", models.CharField(max_length=64)),
                (
                    "task",
                    models.ForeignKey(
                        db_column="task_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="api.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="uploaded_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "task_attachments",
            },
        ),
    ]
