# Generated by Django 6.0 on 2026-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_task_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="in_progress_date",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
