# Generated by Django 6.0 on 2026-01-13 12:18

from django.db import migrations
from django.utils import timezone


def backfill_in_progress_date(apps, schema_editor):
    Task = apps.get_model("api", "Task")
    today = timezone.now().strftime("%Y-%m-%d")
    Task.objects.filter(
        status__in=["In Progress", "Blocked", "Reopen"],
        in_progress_date__isnull=True,
    ).update(in_progress_date=today)
    Task.objects.filter(
        status__in=["In Progress", "Blocked", "Reopen"],
        in_progress_date="",
    ).update(in_progress_date=today)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_task_in_progress_date"),
    ]

    operations = [
        migrations.RunPython(backfill_in_progress_date, migrations.RunPython.noop),
    ]
