# Generated by Django 6.0 on 2026-02-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_memberprofile_leave_dates'),
        ('api', '0017_add_team_fields'),
    ]

    operations = [
    ]
