# Generated by Django 6.0 on 2026-02-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20260204_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.IntegerField(default=200)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_date', models.CharField(max_length=64)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
