"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import boto3
import json
from botocore.exceptions import ClientError

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    if not path.exists():
        return
    try:
        with path.open() as env_file:
            for raw_line in env_file:
                line = raw_line.strip()
                if not line or line.startswith("#"):
                    continue
                if line.startswith("export "):
                    line = line[len("export ") :].strip()
                if "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                if not key:
                    continue
                value = value.strip()
                if (
                    len(value) >= 2
                    and value[0] == value[-1]
                    and value[0] in ("'", '"')
                ):
                    value = value[1:-1]
                os.environ.setdefault(key, value)
    except OSError:
        pass


# Load local env overrides before reading settings.
_load_env_file(BASE_DIR / ".env")
_load_env_file(BASE_DIR / ".env.local")


def get_secret():
    secret_name = "dev/SprintFlow"
    region_name = "ap-south-1"
    profile_name = "whizzc-dev"

    session_kwargs = {}
    # Only apply a named profile when running locally; Lambda uses its execution role
    if not os.environ.get("AWS_EXECUTION_ENV") and profile_name:
        session_kwargs["profile_name"] = profile_name
    if region_name:
        session_kwargs["region_name"] = region_name

    session = boto3.session.Session(**session_kwargs)
    client = session.client(
        service_name="secretsmanager", region_name=region_name)

    try:
        get_secret_value_response = client.get_secret_value(
            SecretId=secret_name)

    except ClientError as e:
        raise e

    secret = get_secret_value_response["SecretString"]
    return json.loads(secret)


secrets = get_secret()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

ENVIRONMENT = os.environ.get("DJANGO_ENV", "production").lower()
IS_PRODUCTION = ENVIRONMENT == "production"
AWS_REGION = os.environ.get("AWS_REGION", "ap-south-1")
AWS_PROFILE = os.environ.get("AWS_PROFILE") or (
    None if os.environ.get("AWS_EXECUTION_ENV") else "whizzc-dev"
)
ATTACHMENTS_BUCKET = os.environ.get("ATTACHMENTS_BUCKET", "whizz-sprint-flow-attachments")
ATTACHMENT_URL_EXPIRES = int(os.environ.get("ATTACHMENT_URL_EXPIRES", "3600"))  # seconds
WORKDAY_HOURS = float(os.environ.get("WORKDAY_HOURS", "8"))
WORKDAY_START_HOUR = float(os.environ.get("WORKDAY_START_HOUR", "10"))
WORKDAY_END_HOUR = float(os.environ.get("WORKDAY_END_HOUR", "18"))


# Default domain: prefer env, then secret, fallback to localhost for local dev.
DEFAULT_APP_DOMAIN = os.environ.get("DEFAULT_APP_DOMAIN") or secrets["APP_DOMAIN"]
APP_DOMAIN = os.environ.get("APP_DOMAIN") or DEFAULT_APP_DOMAIN

def _split_env_list(value: str | None):
    return [item.strip() for item in (value or "").split(",") if item.strip()]

def _split_int_list(value: str | None):
    result: list[int] = []
    for item in _split_env_list(value):
        try:
            result.append(int(item))
        except ValueError:
            continue
    return result

def _env_flag(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "y", "on")

# Weekends/holidays for business-day calculations (e.g. "5,6" for Sat/Sun).
WEEKEND_DAYS = _split_int_list(os.environ.get("WEEKEND_DAYS")) or [5, 6]
HOLIDAY_DATES = _split_env_list(os.environ.get("HOLIDAY_DATES"))

# Use HTTPS for production by default; local dev defaults to the Vite port.
DEFAULT_FRONTEND_ORIGIN = (
    f"https://{APP_DOMAIN}" if IS_PRODUCTION else f"http://{APP_DOMAIN}:5173"
)
FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", DEFAULT_FRONTEND_ORIGIN)
# Allow explicit additional origins via env and a known cloud domain fallback to avoid
# misconfiguration-driven CORS/CSRF blocks in deployments.
EXTRA_ORIGINS = _split_env_list(os.environ.get("EXTRA_ORIGINS"))
DEFAULT_CLOUD_FRONTEND = (
    os.environ.get("DEFAULT_CLOUD_FRONTEND")
    or secrets.get("DEFAULT_CLOUD_FRONTEND")
    or (f"https://{APP_DOMAIN}" if APP_DOMAIN else None)
)
_fallback_frontend_origins = [FRONTEND_ORIGIN, DEFAULT_CLOUD_FRONTEND]
ALL_FRONTEND_ORIGINS = list(
    dict.fromkeys(origin for origin in (_fallback_frontend_origins + EXTRA_ORIGINS) if origin)
)
LOCAL_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:8080",
    "http://localhost:5173",
    "http://localhost:4173",
]

# Email notifications (SMTP in production, console backend by default in local dev).
EMAIL_NOTIFICATIONS_ENABLED = True
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = secrets["EMAIL_HOST"]
EMAIL_PORT = 587
EMAIL_HOST_USER = secrets["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = secrets["EMAIL_HOST_PASSWORD"]
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = secrets["DEFAULT_FROM_EMAIL"]

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", 'django-insecure-au!j--qpw4z#(9wg&l9#uizkfqty^58ujiai+t&*n$srs+#5%2'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = [
    host
    for host in [
        "localhost",
        "127.0.0.1",
        APP_DOMAIN,
        f".{APP_DOMAIN}",
        secrets["BACKEND_HOST"],
        ".execute-api.ap-south-1.amazonaws.com",
    ]
    if host
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'api.middleware.NoCacheAuthMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': secrets['dbname'],
        'USER': secrets['username'],
        'PASSWORD': secrets['password'],
        'HOST': secrets['host'],
        'PORT': secrets['port'],
        'OPTIONS': {
            'connect_timeout': 30,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
        'CONN_MAX_AGE': 300  # 5 minutes
    }
}

# Django REST Framework configuration
# Currently we use only SessionMemberAuthentication, which relies on Django's
# session-based auth and is sufficient for our browser-based use cases.
# If API clients requiring stateless or external auth are introduced, additional
# authentication classes (e.g., token- or JWT-based) can be added here.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["api.authentication.SessionMemberAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-in'

TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = LOCAL_ORIGINS + ALL_FRONTEND_ORIGINS
CSRF_TRUSTED_ORIGINS = LOCAL_ORIGINS + ALL_FRONTEND_ORIGINS
# Log CSRF validation failures with a custom view for easier debugging of 403s.
CSRF_FAILURE_VIEW = "api.views.csrf_failure"
# Always keep host-only cookies in development so localhost domains work even if
# APP_DOMAIN is set to a non-local value. In production, scope cookies to the
# configured app domain to allow subdomain access, but avoid setting Secure/None
# for localhost so local HTTP testing keeps the session cookie.
COOKIE_DOMAIN_OVERRIDE = secrets["COOKIE_DOMAIN"]
IS_LOCAL_DOMAIN = APP_DOMAIN in ("localhost", "127.0.0.1") or COOKIE_DOMAIN_OVERRIDE in (
    "localhost",
    "127.0.0.1",
)

def _normalize_cookie_domain(value: str | None) -> str | None:
    if not value:
        return None
    if value in ("localhost", "127.0.0.1"):
        return value
    return value if value.startswith(".") else f".{value}"

if IS_PRODUCTION:
    if COOKIE_DOMAIN_OVERRIDE:
        COOKIE_DOMAIN = _normalize_cookie_domain(COOKIE_DOMAIN_OVERRIDE)
    else:
        COOKIE_DOMAIN = None if IS_LOCAL_DOMAIN else _normalize_cookie_domain(APP_DOMAIN)
else:
    COOKIE_DOMAIN = None
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
SESSION_COOKIE_SAMESITE = "None" if IS_PRODUCTION and not IS_LOCAL_DOMAIN else "Lax"
CSRF_COOKIE_SAMESITE = "None" if IS_PRODUCTION and not IS_LOCAL_DOMAIN else "Lax"
SESSION_COOKIE_SECURE = IS_PRODUCTION and not IS_LOCAL_DOMAIN
CSRF_COOKIE_SECURE = IS_PRODUCTION and not IS_LOCAL_DOMAIN
APPEND_SLASH = False
AUTH_PASSWORD_VALIDATORS = []

# Honor HTTPS headers when behind a proxy/load balancer
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
